### ISSUE TITLE
LS to HC and Latch problems

### ISSUE THREAD

**Issue by Bucketgiggle** [GigglePaste/BSPD#4]
~~Replace the LS series digital gates with HC series. Look into reset for the nor gate SR Latch. If possible, replace SR latch with JK latch.~~

**Comment by Bucketgiggle** [comment]
It was a stupid thing to say that a JK latch exists. No, it is not possible to replace the SR Latch with a JK latch. This is because a so called "JK Latch" depends on the CLK to rid itself of the Invalid/Illegal state for the SR latch's 1 1 o/p. Making it a flipflop. Dropping the idea, solution is to look into the RESET mechanism of a SR latch.

**Comment by GigglePaste** [comment]
The higher voltage logic gates are added, this allows for us to directly use the GLV power supply. After  the changes, the entire logic of the board now runs on 12V.
