### ISSUE TITLE
Pullup resistors and time verification

### ISSUE THREAD

**Issue by Bucketgiggle** [GigglePaste/BSPD#5]
Get the pullup resistor values. Verify the time of 500ms and 10s. Keep capacitor value of 0.1uF

**Comment by GigglePaste** [comment]
Changed the values of capacitor to 1uF for 500ms and 10uF for 10s. The problem being if the capacitance is too small, the charging curve plauteaus extremely fast. Hence the relatively large capacitance values.

**Comment by GigglePaste** [comment]
Pullup resistors are just meant not to load the wires and hence a small 10k resistor is more than enough for a current of 1.2mA, which is small enough to not destroy the components. Could change the value for a large one if necessary, until then the problem is fixed.

**Comment by GigglePaste** [comment]
Finally, the NPN transistor is used to discharge the capcitor instantly by using a not gate made using NOR gates connected to its base. Just need to figure out the values of these NPN transistors for a current of 10mA and VCE of ~11.7V. That can be done also when making the PCB. Issue solved for now.
